### ISSUE TITLE
could i reproduce the results using this code?

### ISSUE THREAD

**Issue by kyungjoongjeong** [emreg00/proximity#1]
i installed all packages and environments.

![image](https://user-images.githubusercontent.com/61663318/99645774-f80b1600-2a92-11eb-8c79-9b477595c30f.png)

there is some problem. is this a sample code?

It looks like a part of some full code.

**Comment by STALICLA-RnD** [comment]
Dear Kyung,

Thanks for your interest in this project. I see that you had tried to run the notebook with the default (Python) kernel. Please note that this notebook requires the R kernel for Jupyter (see the requirements on the README) as it is written in R.

Hope this helps.

Best of luck!

**Comment by emreg00** [comment]
Dear Kyung,

Thanks for your interest in this project. I see that you had tried to run the notebook with the default (Python) kernel. Please note that this notebook requires the R kernel for Jupyter (see the requirements on the README) as it is written in R.

Hope this helps.

Best of luck!

**Comment by kyungjoongjeong** [comment]
Thank you for your kind support.
I'm the first time R kernel for Jupyter. I should have changed the python kernel to R in Jupyter. I didn't recognize it.
Anyway, now I reproduced your results ;)
